### ISSUE TITLE
web interfaces ui

### ISSUE THREAD

**Issue by roscopecoltran** [jmmcatee/goschemaform#1]
Hi,

Hope you are all well !

I was wondering how **goschemaform** could be integrated to a web admin interfaces to browse content depending on the database schema. I am writing a gin/gorm/sqlite/mysql/postgres/mongo rest api and wanted to edit content dynamically through forms.

Found some project related toward this goal:
- https://github.com/marmelab/ng-admin
- https://github.com/marmelab/admin-on-rest
- https://github.com/marmelab/admin-on-rest-demo
- https://github.com/Onefootball/entity-rest-api

But none if actually parsing the models in order to generate dynamically a web interfaces.

Was **goschemaform** trying to reach a similar goal ? Do you have any advice on the best way to use **goschemaform** in such setup ?

Have a good day !

Cheers,
Richard

**Comment by jmmcatee** [comment]
Richard,

This repo was focused on building a Go package that could make generating JSON schema definitions for Angular 1 form generation tools. Specifically, it follows the format of [http://schemaform.io/](http://schemaform.io/). We use this as park of another project to allow Go programmers to create a semi-complex form in the Angular 1 without writing any HTML and JavaScript. Hope that answers your question. If not let me know what else I can help with.

Thanks,
Michael
